//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.0
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poker.Traduction.English {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Poker.Traduction.English.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access.
        /// </summary>
        internal static string Acces {
            get {
                return ResourceManager.GetString("Acces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} fold.
        /// </summary>
        internal static string ActionJette {
            get {
                return ResourceManager.GetString("ActionJette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} bets {1}.
        /// </summary>
        internal static string ActionMise {
            get {
                return ResourceManager.GetString("ActionMise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} check.
        /// </summary>
        internal static string ActionParole {
            get {
                return ResourceManager.GetString("ActionParole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} raises to {1}.
        /// </summary>
        internal static string ActionRelance {
            get {
                return ResourceManager.GetString("ActionRelance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} calls.
        /// </summary>
        internal static string ActionSuit {
            get {
                return ResourceManager.GetString("ActionSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à all-in for {0} ({1}) !!!!.
        /// </summary>
        internal static string ActionTapis {
            get {
                return ResourceManager.GetString("ActionTapis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Bot.
        /// </summary>
        internal static string AjoutBot {
            get {
                return ResourceManager.GetString("AjoutBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blinds raising.
        /// </summary>
        internal static string AugmentationBlinds {
            get {
                return ResourceManager.GetString("AugmentationBlinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IP adresses of the host.
        /// </summary>
        internal static string BoutonListeIPServeur {
            get {
                return ResourceManager.GetString("BoutonListeIPServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide cards.
        /// </summary>
        internal static string CacherLesCartes {
            get {
                return ResourceManager.GetString("CacherLesCartes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a game ....
        /// </summary>
        internal static string ChoisirPartie {
            get {
                return ResourceManager.GetString("ChoisirPartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Winner : {0}.
        /// </summary>
        internal static string Classement1 {
            get {
                return ResourceManager.GetString("Classement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 10th : {0}.
        /// </summary>
        internal static string Classement10 {
            get {
                return ResourceManager.GetString("Classement10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2nd: {0}.
        /// </summary>
        internal static string Classement2 {
            get {
                return ResourceManager.GetString("Classement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3rd : {0}.
        /// </summary>
        internal static string Classement3 {
            get {
                return ResourceManager.GetString("Classement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4th : {0}.
        /// </summary>
        internal static string Classement4 {
            get {
                return ResourceManager.GetString("Classement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5th : {0}.
        /// </summary>
        internal static string Classement5 {
            get {
                return ResourceManager.GetString("Classement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6th : {0}.
        /// </summary>
        internal static string Classement6 {
            get {
                return ResourceManager.GetString("Classement6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7th : {0}.
        /// </summary>
        internal static string Classement7 {
            get {
                return ResourceManager.GetString("Classement7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8th : {0}.
        /// </summary>
        internal static string Classement8 {
            get {
                return ResourceManager.GetString("Classement8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 9th : {0}.
        /// </summary>
        internal static string Classement9 {
            get {
                return ResourceManager.GetString("Classement9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection....
        /// </summary>
        internal static string ConnexionTitre {
            get {
                return ResourceManager.GetString("ConnexionTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:00}:{1:00}.
        /// </summary>
        internal static string DelaiProchaineBlind {
            get {
                return ResourceManager.GetString("DelaiProchaineBlind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting a new game.
        /// </summary>
        internal static string DemarragePartie {
            get {
                return ResourceManager.GetString("DemarragePartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        internal static string Demarrer {
            get {
                return ResourceManager.GetString("Demarrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Replay.
        /// </summary>
        internal static string DemarrerLecture {
            get {
                return ResourceManager.GetString("DemarrerLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start game.
        /// </summary>
        internal static string DemarrerPartie {
            get {
                return ResourceManager.GetString("DemarrerPartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string DescriptionPartie {
            get {
                return ResourceManager.GetString("DescriptionPartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à As a spectator.
        /// </summary>
        internal static string EnSpectateur {
            get {
                return ResourceManager.GetString("EnSpectateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send.
        /// </summary>
        internal static string Envoyer {
            get {
                return ResourceManager.GetString("Envoyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fatal application error :.
        /// </summary>
        internal static string ErreurApplication {
            get {
                return ResourceManager.GetString("ErreurApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error when deal has changed :.
        /// </summary>
        internal static string ErreurChangementDonne {
            get {
                return ResourceManager.GetString("ErreurChangementDonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while chosing a game :.
        /// </summary>
        internal static string ErreurChoixPartie {
            get {
                return ResourceManager.GetString("ErreurChoixPartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur during connection : server communication troubles.
        /// </summary>
        internal static string ErreurConnection {
            get {
                return ResourceManager.GetString("ErreurConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur during connection : This name has already be chosen.
        /// </summary>
        internal static string ErreurConnectionNomDejaUtilise {
            get {
                return ResourceManager.GetString("ErreurConnectionNomDejaUtilise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur during connection : This name is incorrect.
        /// </summary>
        internal static string ErreurConnectionNomIncorrect {
            get {
                return ResourceManager.GetString("ErreurConnectionNomIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur during connection : The game has already started.
        /// </summary>
        internal static string ErreurConnectionPartieEnCours {
            get {
                return ResourceManager.GetString("ErreurConnectionPartieEnCours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur during connection : Too many players already connected.
        /// </summary>
        internal static string ErreurConnectionTropDeJoueurs {
            get {
                return ResourceManager.GetString("ErreurConnectionTropDeJoueurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while starting the host :.
        /// </summary>
        internal static string ErreurDemarrageServeur {
            get {
                return ResourceManager.GetString("ErreurDemarrageServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture error : the amount must be a positive integer.
        /// </summary>
        internal static string ErreurSaisie {
            get {
                return ResourceManager.GetString("ErreurSaisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flop.
        /// </summary>
        internal static string Flop {
            get {
                return ResourceManager.GetString("Flop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bots management.
        /// </summary>
        internal static string GestionBots {
            get {
                return ResourceManager.GetString("GestionBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Host.
        /// </summary>
        internal static string Heberger {
            get {
                return ResourceManager.GetString("Heberger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blinds raising.
        /// </summary>
        internal static string InfosAugmentationBlinds {
            get {
                return ResourceManager.GetString("InfosAugmentationBlinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} wins the pot of {1}.
        /// </summary>
        internal static string InfosJoueurEmpochePot {
            get {
                return ResourceManager.GetString("InfosJoueurEmpochePot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} wins the pot of {1} with {2}.
        /// </summary>
        internal static string InfosJoueurEmpochePotAvecCombinaison {
            get {
                return ResourceManager.GetString("InfosJoueurEmpochePotAvecCombinaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} win the pot of {1} with {2}.
        /// </summary>
        internal static string InfosJoueursEmpochentPotAvecCombinaison {
            get {
                return ResourceManager.GetString("InfosJoueursEmpochentPotAvecCombinaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fold.
        /// </summary>
        internal static string Jeter {
            get {
                return ResourceManager.GetString("Jeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have chosen to fold but you could check instead. Choose :{\r}{\n}{\t}Yes : to confirm your fold{\r}{\n}{\t}No : to check{\r}{\n}{\t}Cancel : to cancel your choice.
        /// </summary>
        internal static string JeterOuParole {
            get {
                return ResourceManager.GetString("JeterOuParole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game.
        /// </summary>
        internal static string Jeu {
            get {
                return ResourceManager.GetString("Jeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} says : .
        /// </summary>
        internal static string JoueurDit {
            get {
                return ResourceManager.GetString("JoueurDit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Langue {
            get {
                return ResourceManager.GetString("Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected people.
        /// </summary>
        internal static string ListeConnectes {
            get {
                return ResourceManager.GetString("ListeConnectes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of IP adresses for this host :.
        /// </summary>
        internal static string ListeIPServeur {
            get {
                return ResourceManager.GetString("ListeIPServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replay method.
        /// </summary>
        internal static string MethodeLecture {
            get {
                return ResourceManager.GetString("MethodeLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bet = {0}.
        /// </summary>
        internal static string MiseJoueur {
            get {
                return ResourceManager.GetString("MiseJoueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bet.
        /// </summary>
        internal static string Miser {
            get {
                return ResourceManager.GetString("Miser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blind : {0} / {1}.
        /// </summary>
        internal static string MontantBlind {
            get {
                return ResourceManager.GetString("MontantBlind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} / {1}.
        /// </summary>
        internal static string MontantProchaineBlind {
            get {
                return ResourceManager.GetString("MontantProchaineBlind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The raise must be between {0} and {1}.
        /// </summary>
        internal static string MontantRelance {
            get {
                return ResourceManager.GetString("MontantRelance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of deals.
        /// </summary>
        internal static string NombreDonnes {
            get {
                return ResourceManager.GetString("NombreDonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Player&apos;s name.
        /// </summary>
        internal static string NomJoueur {
            get {
                return ResourceManager.GetString("NomJoueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string NomPartie {
            get {
                return ResourceManager.GetString("NomPartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no.
        /// </summary>
        internal static string non {
            get {
                return ResourceManager.GetString("non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New deal.
        /// </summary>
        internal static string NouvelleDonne {
            get {
                return ResourceManager.GetString("NouvelleDonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deal n°.
        /// </summary>
        internal static string NumeroDonneReplay {
            get {
                return ResourceManager.GetString("NumeroDonneReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game options.
        /// </summary>
        internal static string OptionsPartie {
            get {
                return ResourceManager.GetString("OptionsPartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yes.
        /// </summary>
        internal static string oui {
            get {
                return ResourceManager.GetString("oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check.
        /// </summary>
        internal static string Parole {
            get {
                return ResourceManager.GetString("Parole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game.
        /// </summary>
        internal static string Partie {
            get {
                return ResourceManager.GetString("Partie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A game is running. If you quit the application, this game will be lost.{\r}{\n}Do you want to continue ?.
        /// </summary>
        internal static string PartieEnCours {
            get {
                return ResourceManager.GetString("PartieEnCours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} pays big blind of {1}.
        /// </summary>
        internal static string PayeGrosseBlind {
            get {
                return ResourceManager.GetString("PayeGrosseBlind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} pays small blind of {1}.
        /// </summary>
        internal static string PayePetiteBlind {
            get {
                return ResourceManager.GetString("PayePetiteBlind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initial small blind.
        /// </summary>
        internal static string PetiteBlindInitiale {
            get {
                return ResourceManager.GetString("PetiteBlindInitiale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Big blind : {0}.
        /// </summary>
        internal static string PokerPanelGrosseBlind {
            get {
                return ResourceManager.GetString("PokerPanelGrosseBlind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bet : {0}.
        /// </summary>
        internal static string PokerPanelMise {
            get {
                return ResourceManager.GetString("PokerPanelMise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check.
        /// </summary>
        internal static string PokerPanelParole {
            get {
                return ResourceManager.GetString("PokerPanelParole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fold.
        /// </summary>
        internal static string PokerPanelPasse {
            get {
                return ResourceManager.GetString("PokerPanelPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sm. blind : {0}.
        /// </summary>
        internal static string PokerPanelPetiteBlind {
            get {
                return ResourceManager.GetString("PokerPanelPetiteBlind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raise : {0}.
        /// </summary>
        internal static string PokerPanelRelance {
            get {
                return ResourceManager.GetString("PokerPanelRelance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calls : {0}.
        /// </summary>
        internal static string PokerPanelSuit {
            get {
                return ResourceManager.GetString("PokerPanelSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All-In : {0}.
        /// </summary>
        internal static string PokerPanelTapis {
            get {
                return ResourceManager.GetString("PokerPanelTapis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pot : {0}.
        /// </summary>
        internal static string Pot {
            get {
                return ResourceManager.GetString("Pot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next blinds : .
        /// </summary>
        internal static string ProchainesBlinds {
            get {
                return ResourceManager.GetString("ProchainesBlinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string Quitter {
            get {
                return ResourceManager.GetString("Quitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Join.
        /// </summary>
        internal static string Rejoindre {
            get {
                return ResourceManager.GetString("Rejoindre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raise.
        /// </summary>
        internal static string Relancer {
            get {
                return ResourceManager.GetString("Relancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replay.
        /// </summary>
        internal static string Replay {
            get {
                return ResourceManager.GetString("Replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à River.
        /// </summary>
        internal static string River {
            get {
                return ResourceManager.GetString("River", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select game.
        /// </summary>
        internal static string SelectionParties {
            get {
                return ResourceManager.GetString("SelectionParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call (+{0}).
        /// </summary>
        internal static string Suivre {
            get {
                return ResourceManager.GetString("Suivre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All in.
        /// </summary>
        internal static string Tapis {
            get {
                return ResourceManager.GetString("Tapis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initial pot.
        /// </summary>
        internal static string TapisInitial {
            get {
                return ResourceManager.GetString("TapisInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pot = {0}.
        /// </summary>
        internal static string TapisJoueur {
            get {
                return ResourceManager.GetString("TapisJoueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time.
        /// </summary>
        internal static string Temps {
            get {
                return ResourceManager.GetString("Temps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time-out new deal.
        /// </summary>
        internal static string TimeOutDonne {
            get {
                return ResourceManager.GetString("TimeOutDonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time-out player.
        /// </summary>
        internal static string TimeOutJoueur {
            get {
                return ResourceManager.GetString("TimeOutJoueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WPF Poker Texas Hold&apos;em .
        /// </summary>
        internal static string TitreClient {
            get {
                return ResourceManager.GetString("TitreClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Turn.
        /// </summary>
        internal static string Turn {
            get {
                return ResourceManager.GetString("Turn", resourceCulture);
            }
        }
    }
}
